import CustomLink from '@/components/CustomLink';
import { SiteIcon, SocialIcon } from '@/components/Icons';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <h1 className={`${serifTC.className} font-bold text-blue-900`}>
          Home Page 123 首頁
        </h1>
        <h2 className={`${serifTC.className} font-black`}>Black 文字</h2>
        <h2 className={sansTC.className}>Regular 文字</h2> */}
        <h1 className={` font-notoSerif font-bold text-blue-900`}>
          Home Page 123 首頁
        </h1>
        <h2 className={` font-notoSerif font-black`}>Black 文字</h2>
        <h2 className=" font-notoSans">Regular 文字</h2>
        <SiteIcon />
        <SocialIcon kind="behance" href="https://google.com" />
        <SocialIcon kind="gmail" href="hl6jo3@gmail.com" />
        {/* <AboutPageIcon src="/images/about-drawing.png" /> */}
        <CustomLink href="https://google.com" />
      </main>
    </>
  );
}
